---
title: 'Consumer Lending in the FinTech Era: Minimizing both risk and bias'
author: "Holden Wright"
output: pdf_document
date: "2024-10-22"
fontsize: 12pt
---

Owning a house is a common dream for many young adults in America. However, for some Americans there are significant institutional road blocks that make it harder to achieve this dream. According to data from the FFIEC, in 2023 African American and Hispanic-White applicants had denial rates for "first lien, one- to four-family, site-built, owner-occupied conventional, closed-end home purchase loans" of 16.6 percent and 12.0 percent respectively. The denial rates for Asian and non-Hispanic-White applicants were much lower at 9.0 percent and 5.8 percent respectively (CFPB 2024). This disparity in approval rates may stem from inherent differences between racial groups in the credit riskiness of individuals applying for loans. Credit riskiness takes into account factors like credit score, loan-to-value (LTV), and other financial data. However, many lending institutions seem to have an inherent bias against minority borrowers even when their credit score and other metrics put them on level terms with non-minority borrowers. This paper analyzes the research methodologies, results, and ethical considerations presented in “Consumer-lending discrimination in the FinTech Era” by Robert Bartlett, Adair Morse, Richard Stanton, and Nancy Wallace, in which the authors aim to show that minorities pay significantly higher interest rates on mortgage loans than non-minorities with equivalent credit risk metrics. To conduct their research the authors construct a data set merging data from a number of different sources to obtain all the variables they deem necessary. On top of proving racial discrimination in lending practices the researchers focus on the difference in discrimination between traditional face-to-face lenders and FinTech lenders who use algorithmic decision making to see if the different methods produce different levels of discrimination.

In the paper's introduction the researchers describe the faults of past studies done on this topic and highlight that much of the past literature suffers from an omitted-variable problem. Lenders have access to borrower information that researchers do not, making it difficult to determine whether differences in interest rates between groups of borrowers are due to discrimination or to credit-risk factors known to the lender but not to the researcher. The authors attempt to remedy this issue by investigating mortgage loan discrimination in a setting where all necessary variables are observed. This is made possible by the role of government-sponsored enterprises (GSEs) and the Federal Housing Administration (FHA). GSEs determine credit-risk pricing adjustments using an 8 by 8 matrix of loan-to-value ratios (LTVs) and credit scores called loan-level price adjustments (LLPAs). In return for paying the associated LLPA fees, GSEs guarantee lenders against any credit risk. The importance that GSEs provide to the author's analysis is that GSEs completely determine the price to be paid that eliminates any credit risk to the lender. Thus any interest-rate differences between loans within a given credit score/LTV grid cell do not reflect a difference in credit risk, and must reflect a form of discrimination. FHA loans work similarly and are based off the GSEs' LLPA grid but are less rigid and do not employ as strict risk-based pricing. For their analysis the researchers create a new merged data set consisting of data from four mortgage data sources: loan-level McDash data compiled by Black Knight Financial Services, property and loan-level data from ATTOM Data Solutions, loan origination data from the Home Mortgage Disclosure Act (HMDA) data, and loan-performance data from Equifax that was pre-merged with the McDash data by Black Knight. Their data set includes loan-level information on income, race, ethnicity, an indicator for if the lender used primarily algorithmic scoring, as well as many other loan metric variables. They focused on two loan-origination vintages: about 5.7 million loans issued between 2009 and 2015 using the full merged data, and 3.2 million loans originated in 2018 and 2019 using the recently expanded 2018–2019 HMDA data. 

The researcher's base model regresses the mortgage interest rate on an indicator for the individual being black or latinx plus dummies for the 64 GSE grid levels interacted with year/month and whether the loan was a cash-out refinance. This model allows the researchers to capture pricing from the grid, as well as different pricing methods for cash-out refinances, differential pricing by lender, and fluctuations over time. Their model also includes a fixed effect loan size since to account for its effect on the interest rate. The researchers then present a table that details the results from running this model on their data. In order to improve the interpretability of the table the researchers show four columns separated into GSE purchase, GSE refinance, FHA purchase, and FHA refinance. The minority indicator variable has a statistically significant coefficient, under a p-value of .01, for all four columns highlighting that discrimination is occurring for all types of mortgage loans. The researchers then run the same regression this time replacing the minority indicator variable with two interaction variables, FinTech x Minority and Non-FinTech x Minority, to assess if FinTech lenders also exhibit discrimination. They find that FinTech lenders exhibit comparable levels of discrimination for GSE loans and lower levels of discrimination for FHA. Despite the lower levels for FHA loans the discrimination is still statistically significant at p-value of .05. 

After running their initial model the researchers then run several more models looking at the impacts of time, specifically the emergence of FinTech lenders creating an environment more conducive to shopping for cheaper rates and the effect of post-2011 regulation meant to reduce the incentive of brokers to place borrowers into high-cost loans, the impact of geography, and additional robustness tests exploring the issues of put-back risk, servicing-cost risk, and HMDA ethnicity/race designations. In order to look at the effect of passing time the researchers plot the minority rate differential coefficient over time for each of their four categories, GSE purchase and refinance and FHA purchase and refinance. None of their four graphs exhibit trend or change over time suggesting that neither the introduction of FinTech lending nor changes to regulation has had any notable effect on outcomes. To examine the effect of geography they use census data to analyze whether discrimination is higher in areas with larger minority share. They find that overall mortgage rates are higher for all borrowers in high minority concentrated areas and on top of that discrimination is higher as well. Because of this double effect a minority borrower taking out a GSE purchase loan in the highest concentrated minority-share census tract pays, on average, 13.8 basis points more than an otherwise-equivalent non-minority borrower in the lowest concentrated minority-share census tract. For FHA purchase loans, the difference is even larger at 16.2 basis points.

All of their models up to this point had been run on the 2009-2015 data due to the 2019-2019 data allowing for the researcher to control for points and total up-front loan costs. Borrowers can choose to pay “discount points,” which is an up-front lump sum, to a lender to reduce their loan's interest rate. They can also choose to pay “negative points” to get a credit from the lender, in return for paying a higher loan interest rate. They re-run the same models described above on the 2018-2019 data not controlling for points in order to compare and find similar results with statistically significant coefficients on the minority indicator signalling discrimination. When they run the model that includes FinTech indicators they find that for FHA refinance loans the FinTech x Minority variable actually has a statistically insignificant negative coefficient meaning that for that style of loan FinTechs exhibit no discrimination. After comparing all of the previously run models on the more recent data they run a new model that controls for points. This model does not exhibit any differences in findings from their earlier models and again points to discrimination. 

These discriminatory lending practices are yet another institutional road block for minorities that makes success that much harder for them compared to non-minorities. Even in the age of FinTech lenders and algorithmic decision making major interest rate differences still exist for otherwise equivalent minority borrowers. The discrimination is even further exacerbated when looking at high minority concentrated geographical areas versus low minority concentration areas. This makes it even harder for individuals to improve their circumstances and continues to perpetuate the vicious cycle of racism. As shown in the researcher's model that included geographical controls minority buyers in high minority concentrated areas pay 13.8 basis points more for GSE purchase loans and 16.2 basis points more for FHA purchase loans. To put these magnitudes into a more understandable context the researchers estimate that this translates into Latinx/Black borrowers paying over $450 million extra in interest per year. 

The small differences in discrimination between FinTech and Non-FinTech lenders suggests that the face-to-face aspect of traditional lending is a primary contributor to the institutional bias against minority borrowers. As worrisome as this is, the fact that FinTech's algorithmic decision making only reduces bias for FHA refinance loans and still discriminates heavily for the other three types of mortgage loans looked at in this study is even more concerning and signals that there is still a lot that needs to change in how lenders evaluate borrowers and decide the terms of their loan.

\newpage

References

“FFIEC Publishes 2023 Data on Mortgage Lending | Consumer Financial Protection Bureau.” Consumer Financial Protection Bureau, 11 July 2024, www.consumerfinance.gov/about-us/newsroom/ffiec-publishes-2023-data-on-mortgage-lending.

Bartlett, Robert, et al. “Consumer-lending Discrimination in the FinTech Era.” Journal of Financial Economics, vol. 143, no. 1, May 2021, pp. 30–56, doi:10.1016/j.jfineco.2021.05.047.










